import { act, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { BriefView } from "../features/artifact-viewer/ArtifactViewer";

// Sample markdown that mirrors render_brief() output structure
const sampleBrief = `# Research Brief

**Strategy:** Consensus | **Sources:** 2/2 completed

---

## Key Themes

### Performance Optimization

**Agreement:** Strong agreement | Both sources recommend caching.

- Use Redis for session caching *(claude/default, codex/default)*
- Implement connection pooling *(claude/default)*

**Disagreements:**

- Cache invalidation strategy
  - **TTL-based** — claude/default
  - **Event-driven** — codex/adversarial

## Recommendations

- **[High]** Implement Redis caching *(claude/default, codex/default)*
- **[Medium]** Add connection pooling *(claude/default)*

## Uncertainties

- Load testing data is limited — *only tested with synthetic traffic*

## Source Coverage

| Provider | Perspective | Status |
|----------|-------------|--------|
| claude | default | completed |
| codex | default | completed |

---

*Generated by Multi-Model Synthesizer — Consensus strategy*
`;

const sampleWithCode = `# Brief

Some text.

\`\`\`json
{ "key": "value" }
\`\`\`
`;

describe("BriefView", () => {
	it("shows empty state when brief is null", () => {
		render(<BriefView brief={null} />);
		expect(screen.getByText("No brief available. Run synthesis first.")).toBeDefined();
	});

	it("renders h1 heading from markdown", () => {
		render(<BriefView brief={sampleBrief} />);
		const heading = screen.getByRole("heading", { level: 1 });
		expect(heading.textContent).toBe("Research Brief");
	});

	it("renders h2 headings from markdown", () => {
		render(<BriefView brief={sampleBrief} />);
		const h2s = screen.getAllByRole("heading", { level: 2 });
		const labels = h2s.map((h) => h.textContent);
		expect(labels).toContain("Key Themes");
		expect(labels).toContain("Recommendations");
		expect(labels).toContain("Source Coverage");
	});

	it("renders h3 headings from markdown", () => {
		render(<BriefView brief={sampleBrief} />);
		const h3 = screen.getByRole("heading", { level: 3 });
		expect(h3.textContent).toBe("Performance Optimization");
	});

	it("renders GFM table with headers", () => {
		render(<BriefView brief={sampleBrief} />);
		const table = screen.getByRole("table");
		expect(table).toBeDefined();
		expect(screen.getByRole("columnheader", { name: /Provider/i })).toBeDefined();
		expect(screen.getByRole("columnheader", { name: /Perspective/i })).toBeDefined();
		expect(screen.getByRole("columnheader", { name: /Status/i })).toBeDefined();
	});

	it("renders table data cells", () => {
		render(<BriefView brief={sampleBrief} />);
		const cells = screen.getAllByRole("cell");
		const cellTexts = cells.map((c) => c.textContent);
		expect(cellTexts).toContain("claude");
		expect(cellTexts).toContain("completed");
	});

	it("renders blockquote for disagreements", () => {
		// The brief doesn't use blockquote syntax for disagreements,
		// but let's test with a brief that has a blockquote
		const briefWithQuote = "# Test\n\n> **Note:** 1 source(s) did not complete.\n";
		const { container } = render(<BriefView brief={briefWithQuote} />);
		const blockquote = container.querySelector("blockquote");
		expect(blockquote).not.toBeNull();
	});

	it("renders list items", () => {
		render(<BriefView brief={sampleBrief} />);
		const listItems = screen.getAllByRole("listitem");
		expect(listItems.length).toBeGreaterThan(0);
	});

	it("renders bold text", () => {
		const { container } = render(<BriefView brief={sampleBrief} />);
		const strongElements = container.querySelectorAll("strong");
		expect(strongElements.length).toBeGreaterThan(0);
	});

	it("renders horizontal rules", () => {
		const { container } = render(<BriefView brief={sampleBrief} />);
		const hrs = container.querySelectorAll("hr");
		expect(hrs.length).toBeGreaterThan(0);
	});

	it("wraps content in brief-prose class", () => {
		const { container } = render(<BriefView brief={sampleBrief} />);
		const wrapper = container.querySelector(".brief-prose");
		expect(wrapper).not.toBeNull();
	});
});

describe("BriefView copy button", () => {
	it("shows copy button on code blocks", () => {
		render(<BriefView brief={sampleWithCode} />);
		expect(screen.getByText("Copy")).toBeDefined();
	});

	it("copies code to clipboard and shows Copied!", async () => {
		const user = userEvent.setup();
		render(<BriefView brief={sampleWithCode} />);

		// Spy on navigator.clipboard.writeText AFTER render —
		// @testing-library/user-event v14 installs its own clipboard polyfill.
		// We spy rather than replace, so the original polyfill is preserved.
		const writeText = vi.spyOn(navigator.clipboard, "writeText");

		const copyButton = screen.getByText("Copy");
		await act(async () => {
			await user.click(copyButton);
		});

		await waitFor(() => {
			expect(writeText).toHaveBeenCalledOnce();
		});

		// The copied text should contain the JSON content
		const copiedText = writeText.mock.calls[0]?.[0] as string;
		expect(copiedText).toContain('"key"');
		expect(copiedText).toContain('"value"');

		// Button should now show "Copied!"
		expect(screen.getByText("Copied!")).toBeDefined();
	});
});
