import { act, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { BriefView } from "../features/artifact-viewer/ArtifactViewer";
import {
	extractHeadings,
	slugify,
	splitSections,
} from "../features/artifact-viewer/components/BriefToC";

// Sample markdown that mirrors render_brief() output structure
const sampleBrief = `# Research Brief

**Strategy:** Consensus | **Sources:** 2/2 completed

---

## Key Themes

### Performance Optimization

**Agreement:** Strong agreement | Both sources recommend caching.

- Use Redis for session caching *(claude/default, codex/default)*
- Implement connection pooling *(claude/default)*

**Disagreements:**

- Cache invalidation strategy
  - **TTL-based** — claude/default
  - **Event-driven** — codex/adversarial

## Recommendations

- **[High]** Implement Redis caching *(claude/default, codex/default)*
- **[Medium]** Add connection pooling *(claude/default)*

## Uncertainties

- Load testing data is limited — *only tested with synthetic traffic*

## Source Coverage

| Provider | Perspective | Status |
|----------|-------------|--------|
| claude | default | completed |
| codex | default | completed |

---

*Generated by Multi-Model Synthesizer — Consensus strategy*
`;

const sampleWithCode = `# Brief

Some text.

\`\`\`json
{ "key": "value" }
\`\`\`
`;

describe("BriefView", () => {
	it("shows empty state when brief is null", () => {
		render(<BriefView brief={null} />);
		expect(screen.getByText("No brief available. Run synthesis first.")).toBeDefined();
	});

	it("renders h1 heading from markdown", () => {
		render(<BriefView brief={sampleBrief} />);
		const heading = screen.getByRole("heading", { level: 1 });
		expect(heading.textContent).toBe("Research Brief");
	});

	it("renders h2 headings from markdown", () => {
		render(<BriefView brief={sampleBrief} />);
		const h2s = screen.getAllByRole("heading", { level: 2 });
		const labels = h2s.map((h) => h.textContent);
		expect(labels).toContain("Key Themes");
		expect(labels).toContain("Recommendations");
		expect(labels).toContain("Source Coverage");
	});

	it("renders h3 headings from markdown", () => {
		render(<BriefView brief={sampleBrief} />);
		const h3 = screen.getByRole("heading", { level: 3 });
		expect(h3.textContent).toBe("Performance Optimization");
	});

	it("renders GFM table with headers", () => {
		render(<BriefView brief={sampleBrief} />);
		const table = screen.getByRole("table");
		expect(table).toBeDefined();
		expect(screen.getByRole("columnheader", { name: /Provider/i })).toBeDefined();
		expect(screen.getByRole("columnheader", { name: /Perspective/i })).toBeDefined();
		expect(screen.getByRole("columnheader", { name: /Status/i })).toBeDefined();
	});

	it("renders table data cells", () => {
		render(<BriefView brief={sampleBrief} />);
		const cells = screen.getAllByRole("cell");
		const cellTexts = cells.map((c) => c.textContent);
		expect(cellTexts).toContain("claude");
		expect(cellTexts).toContain("completed");
	});

	it("renders blockquote for disagreements", () => {
		// The brief doesn't use blockquote syntax for disagreements,
		// but let's test with a brief that has a blockquote
		const briefWithQuote = "# Test\n\n> **Note:** 1 source(s) did not complete.\n";
		const { container } = render(<BriefView brief={briefWithQuote} />);
		const blockquote = container.querySelector("blockquote");
		expect(blockquote).not.toBeNull();
	});

	it("renders list items", () => {
		render(<BriefView brief={sampleBrief} />);
		const listItems = screen.getAllByRole("listitem");
		expect(listItems.length).toBeGreaterThan(0);
	});

	it("renders bold text", () => {
		const { container } = render(<BriefView brief={sampleBrief} />);
		const strongElements = container.querySelectorAll("strong");
		expect(strongElements.length).toBeGreaterThan(0);
	});

	it("renders horizontal rules", () => {
		const { container } = render(<BriefView brief={sampleBrief} />);
		const hrs = container.querySelectorAll("hr");
		expect(hrs.length).toBeGreaterThan(0);
	});

	it("wraps content in brief-prose class", () => {
		const { container } = render(<BriefView brief={sampleBrief} />);
		const wrapper = container.querySelector(".brief-prose");
		expect(wrapper).not.toBeNull();
	});
});

describe("BriefView copy button", () => {
	it("shows copy button on code blocks", () => {
		render(<BriefView brief={sampleWithCode} />);
		expect(screen.getByText("Copy")).toBeDefined();
	});

	it("copies code to clipboard and shows Copied!", async () => {
		const user = userEvent.setup();
		render(<BriefView brief={sampleWithCode} />);

		// Spy on navigator.clipboard.writeText AFTER render —
		// @testing-library/user-event v14 installs its own clipboard polyfill.
		// We spy rather than replace, so the original polyfill is preserved.
		const writeText = vi.spyOn(navigator.clipboard, "writeText");

		const copyButton = screen.getByText("Copy");
		await act(async () => {
			await user.click(copyButton);
		});

		await waitFor(() => {
			expect(writeText).toHaveBeenCalledOnce();
		});

		// The copied text should contain the JSON content
		const copiedText = writeText.mock.calls[0]?.[0] as string;
		expect(copiedText).toContain('"key"');
		expect(copiedText).toContain('"value"');

		// Button should now show "Copied!"
		expect(screen.getByText("Copied!")).toBeDefined();
	});
});

describe("extractHeadings", () => {
	it("extracts h2 and h3 headings from markdown", () => {
		const headings = extractHeadings(sampleBrief);
		const texts = headings.map((h) => h.text);
		expect(texts).toContain("Key Themes");
		expect(texts).toContain("Performance Optimization");
		expect(texts).toContain("Recommendations");
		expect(texts).toContain("Uncertainties");
		expect(texts).toContain("Source Coverage");
	});

	it("assigns correct levels", () => {
		const headings = extractHeadings(sampleBrief);
		const keyThemes = headings.find((h) => h.text === "Key Themes");
		const perfOpt = headings.find((h) => h.text === "Performance Optimization");
		expect(keyThemes?.level).toBe(2);
		expect(perfOpt?.level).toBe(3);
	});

	it("ignores headings inside backtick code blocks", () => {
		const md = "## Real\n\n```\n## Not a heading\n```\n\n## Also Real\n";
		const headings = extractHeadings(md);
		expect(headings).toHaveLength(2);
		expect(headings.map((h) => h.text)).toEqual(["Real", "Also Real"]);
	});

	it("ignores headings inside tilde code blocks", () => {
		const md = "## Real\n\n~~~\n## Not a heading\n~~~\n\n## Also Real\n";
		const headings = extractHeadings(md);
		expect(headings).toHaveLength(2);
		expect(headings.map((h) => h.text)).toEqual(["Real", "Also Real"]);
	});

	it("deduplicates IDs for duplicate heading text", () => {
		const md = "## Summary\n\n## Details\n\n## Summary\n";
		const headings = extractHeadings(md);
		expect(headings.map((h) => h.id)).toEqual(["summary", "details", "summary-2"]);
	});

	it("strips markdown link syntax from heading text for IDs", () => {
		const md = "## [Link Text](https://example.com) Section\n";
		const headings = extractHeadings(md);
		expect(headings[0]?.id).toBe("link-text-section");
	});

	it("does not extract h1 headings", () => {
		const headings = extractHeadings(sampleBrief);
		const h1 = headings.find((h) => h.text === "Research Brief");
		expect(h1).toBeUndefined();
	});

	it("generates slugified IDs", () => {
		expect(slugify("Key Themes")).toBe("key-themes");
		expect(slugify("Performance Optimization")).toBe("performance-optimization");
		expect(slugify("Source Coverage")).toBe("source-coverage");
	});
});

describe("BriefView table of contents", () => {
	it("renders ToC sidebar with heading links", () => {
		render(<BriefView brief={sampleBrief} />);
		expect(screen.getByText("Contents")).toBeDefined();
		expect(screen.getByRole("navigation", { name: "Table of contents" })).toBeDefined();
	});

	it("renders ToC entries for h2 headings", () => {
		render(<BriefView brief={sampleBrief} />);
		// ToC buttons should exist alongside the rendered headings
		const tocNav = screen.getByRole("navigation", { name: "Table of contents" });
		const buttons = tocNav.querySelectorAll("button");
		const buttonTexts = Array.from(buttons).map((b) => b.textContent);
		expect(buttonTexts).toContain("Key Themes");
		expect(buttonTexts).toContain("Recommendations");
		expect(buttonTexts).toContain("Source Coverage");
	});

	it("renders ToC entries for h3 headings", () => {
		render(<BriefView brief={sampleBrief} />);
		const tocNav = screen.getByRole("navigation", { name: "Table of contents" });
		const buttons = tocNav.querySelectorAll("button");
		const buttonTexts = Array.from(buttons).map((b) => b.textContent);
		expect(buttonTexts).toContain("Performance Optimization");
	});

	it("adds id attributes to rendered h2 headings", () => {
		const { container } = render(<BriefView brief={sampleBrief} />);
		const h2 = container.querySelector('h2[id="key-themes"]');
		expect(h2).not.toBeNull();
		expect(h2?.textContent).toBe("Key Themes");
	});

	it("adds id attributes to rendered h3 headings", () => {
		const { container } = render(<BriefView brief={sampleBrief} />);
		const h3 = container.querySelector('h3[id="performance-optimization"]');
		expect(h3).not.toBeNull();
	});

	it("calls scrollIntoView when ToC link is clicked", async () => {
		const user = userEvent.setup();
		const { container } = render(<BriefView brief={sampleBrief} />);

		// Mock scrollIntoView on the target heading
		const targetH2 = container.querySelector('h2[id="recommendations"]');
		if (!targetH2) throw new Error("Expected h2#recommendations to exist");
		const scrollMock = vi.fn();
		targetH2.scrollIntoView = scrollMock;

		// Find and click the ToC button
		const tocNav = screen.getByRole("navigation", { name: "Table of contents" });
		const tocButtons = tocNav.querySelectorAll("button");
		const recButton = Array.from(tocButtons).find((b) => b.textContent === "Recommendations");
		if (!recButton) throw new Error("Expected Recommendations button in ToC");

		await user.click(recButton);
		expect(scrollMock).toHaveBeenCalledOnce();
		expect(scrollMock).toHaveBeenCalledWith({ behavior: "smooth", block: "start" });
	});

	it("does not render ToC when brief has no h2/h3 headings", () => {
		const simpleMarkdown = "# Title\n\nJust a paragraph.\n";
		render(<BriefView brief={simpleMarkdown} />);
		expect(screen.queryByText("Contents")).toBeNull();
	});
});

describe("splitSections", () => {
	it("splits markdown at h2 boundaries", () => {
		const { sections } = splitSections(sampleBrief);
		expect(sections.map((s) => s.heading)).toEqual([
			"Key Themes",
			"Recommendations",
			"Uncertainties",
			"Source Coverage",
		]);
	});

	it("extracts preamble content before first h2", () => {
		const { preamble } = splitSections(sampleBrief);
		expect(preamble).toContain("# Research Brief");
		expect(preamble).toContain("**Strategy:**");
	});

	it("assigns correct slugified IDs to sections", () => {
		const { sections } = splitSections(sampleBrief);
		expect(sections.map((s) => s.id)).toEqual([
			"key-themes",
			"recommendations",
			"uncertainties",
			"source-coverage",
		]);
	});

	it("includes body content for each section", () => {
		const { sections } = splitSections(sampleBrief);
		const keyThemes = sections.find((s) => s.heading === "Key Themes");
		expect(keyThemes?.body).toContain("### Performance Optimization");
		const coverage = sections.find((s) => s.heading === "Source Coverage");
		expect(coverage?.body).toContain("| Provider");
	});

	it("ignores h2 headings inside backtick code blocks", () => {
		const md =
			"# Title\n\n## Real\n\nContent\n\n```\n## Not a heading\n```\n\n## Also Real\n\nMore\n";
		const { sections } = splitSections(md);
		expect(sections.map((s) => s.heading)).toEqual(["Real", "Also Real"]);
	});

	it("ignores h2 headings inside tilde code blocks", () => {
		const md = "## Real\n\nContent\n\n~~~\n## Not a heading\n~~~\n\n## Also Real\n\nMore\n";
		const { sections } = splitSections(md);
		expect(sections.map((s) => s.heading)).toEqual(["Real", "Also Real"]);
	});

	it("handles brief with no h2 headings (preamble only)", () => {
		const md = "# Title\n\nJust text.\n";
		const { preamble, sections } = splitSections(md);
		expect(preamble).toContain("# Title");
		expect(sections).toHaveLength(0);
	});

	it("deduplicates IDs for repeated heading text", () => {
		const md = "## Summary\n\nA\n\n## Details\n\nB\n\n## Summary\n\nC\n";
		const { sections } = splitSections(md);
		expect(sections.map((s) => s.id)).toEqual(["summary", "details", "summary-2"]);
	});

	it("returns h2IdCounts for pre-seeding heading components", () => {
		const { h2IdCounts } = splitSections(sampleBrief);
		expect(h2IdCounts.get("key-themes")).toBe(1);
		expect(h2IdCounts.get("recommendations")).toBe(1);
	});
});

describe("BriefView collapsible sections", () => {
	it("renders details elements for each h2 section", () => {
		const { container } = render(<BriefView brief={sampleBrief} />);
		const details = container.querySelectorAll("details.collapsible-section");
		expect(details).toHaveLength(4);
	});

	it("first 3 sections are open by default", () => {
		const { container } = render(<BriefView brief={sampleBrief} />);
		const details = container.querySelectorAll("details.collapsible-section");
		expect((details[0] as HTMLDetailsElement).open).toBe(true);
		expect((details[1] as HTMLDetailsElement).open).toBe(true);
		expect((details[2] as HTMLDetailsElement).open).toBe(true);
		expect((details[3] as HTMLDetailsElement).open).toBe(false);
	});

	it("h2 headings are inside summary elements", () => {
		const { container } = render(<BriefView brief={sampleBrief} />);
		const summaries = container.querySelectorAll("summary.collapsible-summary");
		expect(summaries).toHaveLength(4);
		const headingTexts = Array.from(summaries).map((s) => s.querySelector("h2")?.textContent);
		expect(headingTexts).toContain("Key Themes");
		expect(headingTexts).toContain("Recommendations");
	});

	it("expand all opens all sections", async () => {
		const user = userEvent.setup();
		const { container } = render(<BriefView brief={sampleBrief} />);

		await user.click(screen.getByText("Expand all"));

		const details = container.querySelectorAll("details.collapsible-section");
		for (const d of details) {
			expect((d as HTMLDetailsElement).open).toBe(true);
		}
	});

	it("collapse all closes all sections", async () => {
		const user = userEvent.setup();
		const { container } = render(<BriefView brief={sampleBrief} />);

		await user.click(screen.getByText("Collapse all"));

		const details = container.querySelectorAll("details.collapsible-section");
		for (const d of details) {
			expect((d as HTMLDetailsElement).open).toBe(false);
		}
	});

	it("shows expand/collapse controls when sections exist", () => {
		render(<BriefView brief={sampleBrief} />);
		expect(screen.getByText("Expand all")).toBeDefined();
		expect(screen.getByText("Collapse all")).toBeDefined();
	});

	it("does not show expand/collapse controls when no h2 sections", () => {
		const simpleMarkdown = "# Title\n\nJust a paragraph.\n";
		render(<BriefView brief={simpleMarkdown} />);
		expect(screen.queryByText("Expand all")).toBeNull();
		expect(screen.queryByText("Collapse all")).toBeNull();
	});

	it("renders section body content inside details", () => {
		const { container } = render(<BriefView brief={sampleBrief} />);
		const firstDetails = container.querySelector("details.collapsible-section");
		expect(firstDetails?.textContent).toContain("Performance Optimization");
	});
});
